Restore CODE_OF_CONDUCT.md from the wiki
privacyguides/.github pull request #2
Opened 2021-11-08 12:59 UTC by Mikaela

Resolves: #1

2021-11-08 13:00 UTC, Mikaela commented
It's in mediawiki syntax as I noticed it can be gotten out of Wayback Machine easily, I need to leave right now though, so I will return to it later and hopefully get it to markdown easily with pandoc with manual corrections where needed.

E.g. it still refers to Tools.

2021-11-08 15:13 UTC, Mikaela commented on CODE_OF_CONDUCT.md
> +*Compliance Team* and *Core Team* Members and how much may be
These *emphatised* parts used to be links, but I have no idea where they were going to, so I just turned them like this as a note to fix them or discuss who these people are.

2021-11-21 21:49 UTC, freddy-m approved these changes
Happy for someone to merge this. cc @dngray

2021-11-23 06:35 UTC, dngray requested changes
Few things:

- What does this actually add over the original CoC? To me it t seems like it spells things out a bit more but that is all. I do believe it creates an opening for rule lawyering, rather than giving moderators discretion to remove/warn people of unwanted behavior.
- I do think we should wait to see @jonaharagon's thoughts on this before merging, as he decidedly didn't bring the PrivacyTools CoC forward
- I think we're too small for a specially designated "Internal Compliance Officer", what if the complaint is against the person wearing that hat
- I also think we're more than capable writing our own CoC and don't need the help of contributor-covenant.org to do that.

2022-05-20 23:45 UTC, jonaharagon commented
Missed this, but I'm inclined to agree with @dngray, I think avoiding unnecessary complexities is an important part of our new direction, and I think the CoC as proposed here will encourage the "rule lawyering" mentioned, whereas the current CoC gives us more flexibility and discretion over community situations.

2022-05-20 23:45 UTC, closed without merging